//This function is called whenever a user adds a new item.
//Firebase generates a unique id for each item automatically.
//The frontend will call this and then update its local state.

import { ref, push, set } from "firebase/database";
import { database } from "./firebaseConfig";

// Function to add a new inventory item
export const addInventoryItem = async (item) => {
  // Create reference to "inventory" node in Firebase
  const inventoryRef = ref(database, "inventory");

  // Push creates a new unique child node under inventory
  const newItemRef = push(inventoryRef);

  // Set the data for the new item
  await set(newItemRef, {
    id: newItemRef.key,      // unique key generated by Firebase
    name: item.name,         // item name from frontend
    stock: item.stock,       // current stock quantity
    threshold: item.threshold // low stock threshold
  });

  // Return the Firebase-generated ID for frontend state update
  return newItemRef.key;
};
